name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: say 'Hi'
      run: echo "Let's work" 
    - name: build test docker
      run: |
        cd test/
        docker build -t cpp-sample .
    - name: run test docker
      run: docker run cpp-sample
    - name: build clean docker
      run: docker build -t alcatraz913/automated_pipeline_training:ver_$GITHUB_RUN_NUMBER .    
      
